#include "streaming_rolling.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <map>
#include <set>
#include <stdexcept>
#include <tuple>

namespace leo::adaptive::tracking::research::streaming_rolling {
namespace {
constexpr double ns=1e9;
struct Key { int receiver,channel; std::string edge; double rf; bool operator<(const Key&o)const{return std::tie(receiver,channel,edge,rf)<std::tie(o.receiver,o.channel,o.edge,o.rf);} };
struct P { const tracking::Candidate* c; double t,raw,w; };
struct G { std::string id; double t; std::vector<std::size_t> p; };
struct Fit { double t,f,r,rms,u; };
struct H { std::vector<std::size_t> p; std::vector<double> f; Fit fit; double score{}; };

bool digest(const std::string&s){return s.size()==71&&s.compare(0,7,"sha256:")==0&&std::all_of(s.begin()+7,s.end(),[](char c){return std::isxdigit(static_cast<unsigned char>(c));});}
double weight(const tracking::Candidate&c){return std::max(.1,std::min(16.0,std::max(0.0,c.margin)/std::max(.02,c.control_score)));}
double wrap(double x,double spacing){x=std::fmod(x+spacing/2,spacing);if(x<0)x+=spacing;return x-spacing/2;}
void validate(const std::vector<tracking::Candidate>&in,const Config&c){
 if(in.empty()||in.size()>c.maximum_input_points||!(c.window_s==4||c.window_s==8||c.window_s==12)||c.maximum_fit_points<2||c.maximum_fit_points>32||c.residual_gate_hz<=0||c.maximum_uncertainty_hz<0||c.maximum_uncertainty_hz>2500||c.minimum_rate_hz_per_s>=c.maximum_rate_hz_per_s||c.maximum_gap_s<=0||c.minimum_span_s<4||c.minimum_support<8||!c.maximum_active_per_lane||!c.alternatives_per_hypothesis||c.alternatives_per_hypothesis>2)throw std::invalid_argument("invalid streaming rolling config");
 std::set<std::string> ids;std::map<std::string,std::tuple<int,int,std::string,double>> groups;std::map<std::string,std::size_t> counts;
 for(const auto&v:in){std::array<double,5>a{v.actual_rf_hz,v.measured_cfo_hz,v.exact_score,v.control_score,v.margin};if(!digest(v.candidate_id)||!digest(v.source_group_id)||!ids.insert(v.candidate_id).second||std::any_of(a.begin(),a.end(),[](double x){return !std::isfinite(x);})||v.receiver_id<0||v.channel<1||(v.edge!="lower"&&v.edge!="upper")||v.actual_rf_hz<=0||v.support_start_utc_ns<=0||v.support_start_utc_ns>v.support_center_utc_ns||v.support_center_utc_ns>=v.support_end_utc_ns||v.margin<=0)throw std::invalid_argument("invalid streaming rolling candidate");auto authority=std::make_tuple(v.receiver_id,v.channel,v.edge,v.actual_rf_hz);auto q=groups.emplace(v.source_group_id,authority);if(!q.second&&q.first->second!=authority)throw std::invalid_argument("source group changes lane");if(++counts[v.source_group_id]>c.maximum_candidates_per_group)throw std::invalid_argument("source group candidate bound exceeded");}
}
Fit fit(const H&h,const std::vector<P>&p,const Config&c,Stats&s){
 const double origin=p[h.p.back()].t;std::size_t b=h.p.size();while(b&&h.p.size()-b<c.maximum_fit_points&&origin-p[h.p[b-1]].t<=c.window_s)--b;
 double sw=0,sx=0,sy=0,sxx=0,sxy=0;for(std::size_t i=b;i<h.p.size();++i){double x=p[h.p[i]].t-origin,w=p[h.p[i]].w;sw+=w;sx+=w*x;sy+=w*h.f[i];sxx+=w*x*x;sxy+=w*x*h.f[i];}double d=sw*sxx-sx*sx;if(std::abs(d)<1e-12)throw std::runtime_error("singular rolling fit");double r=(sw*sxy-sx*sy)/d,f=(sy-r*sx)/sw,ss=0;for(std::size_t i=b;i<h.p.size();++i){double e=h.f[i]-(f+r*(p[h.p[i]].t-origin));ss+=p[h.p[i]].w*e*e;}double rms=std::sqrt(ss/std::max(sw,1e-12));double span=origin-p[h.p[b]].t;double u=std::min(c.maximum_uncertainty_hz,std::max(250.0,rms+std::max(0.0,2.0-span)*500.0));++s.fits;return{origin,f,r,rms,u};
}
bool better(const H&a,const H&b,const std::vector<P>&p){double as=p[a.p.back()].t-p[a.p.front()].t,bs=p[b.p.back()].t-p[b.p.front()].t;return std::make_tuple(a.p.size(),as,a.score)>std::make_tuple(b.p.size(),bs,b.score);}
tracking::Track output(const H&h,const std::vector<P>&p,const Key&k,std::size_t n,double spacing){
 tracking::Track o;o.segment_id="research-streaming-rolling-segment-"+std::to_string(n);o.tracklet_id="research-streaming-rolling-track-"+std::to_string(n);o.lane={k.channel,k.edge,k.receiver,k.rf};o.start_utc_ns=std::numeric_limits<std::int64_t>::max();o.end_utc_ns=std::numeric_limits<std::int64_t>::min();o.reference_utc_ns=p[h.p.back()].c->support_center_utc_ns;
 double sw=0,sx=0,sy=0,sxx=0,sxy=0;for(std::size_t i=0;i<h.p.size();++i){double x=p[h.p[i]].t-p[h.p.back()].t,w=p[h.p[i]].w;sw+=w;sx+=w*x;sy+=w*h.f[i];sxx+=w*x*x;sxy+=w*x*h.f[i];}double d=sw*sxx-sx*sx;o.normalized_rate_hz_per_s=(sw*sxy-sx*sy)/d;o.normalized_intercept_hz=(sy-o.normalized_rate_hz_per_s*sx)/sw;o.weighted_support=sw;double ss=0,mx=0;for(std::size_t i=0;i<h.p.size();++i){double e=h.f[i]-(o.normalized_intercept_hz+o.normalized_rate_hz_per_s*(p[h.p[i]].t-p[h.p.back()].t));ss+=p[h.p[i]].w*e*e;mx=std::max(mx,std::abs(e));int alias=static_cast<int>(std::llround((p[h.p[i]].raw-h.f[i])/spacing));o.points.push_back({p[h.p[i]].c->candidate_id,p[h.p[i]].c->source_group_id,alias,p[h.p[i]].raw,h.f[i]});o.start_utc_ns=std::min(o.start_utc_ns,p[h.p[i]].c->support_start_utc_ns);o.end_utc_ns=std::max(o.end_utc_ns,p[h.p[i]].c->support_end_utc_ns);}o.residual_rms_hz=std::sqrt(ss/sw);o.residual_max_hz=mx;return o;
}
}

Result reconstruct(const std::vector<tracking::Candidate>&in,const Config&c){validate(in,c);Result result;result.input_candidate_count=in.size();std::map<Key,std::vector<const tracking::Candidate*>> lanes;for(const auto&v:in)lanes[{v.receiver_id,v.channel,v.edge,v.actual_rf_hz}].push_back(&v);result.stats.lanes=lanes.size();
 for(const auto&entry:lanes){const Key&key=entry.first;const double scale=c.canonical_rf_hz/key.rf,spacing=c.alias_spacing_hz*scale;std::vector<P> p;for(auto*v:entry.second)p.push_back({v,v->support_center_utc_ns/ns,v->measured_cfo_hz*scale,weight(*v)});std::sort(p.begin(),p.end(),[](const P&a,const P&b){return std::tie(a.t,a.c->source_group_id,a.c->candidate_id)<std::tie(b.t,b.c->source_group_id,b.c->candidate_id);});std::map<std::string,G> grouped;for(std::size_t i=0;i<p.size();++i){auto&g=grouped[p[i].c->source_group_id];g.id=p[i].c->source_group_id;g.t+=p[i].t;g.p.push_back(i);}std::vector<G> gs;for(auto&item:grouped){item.second.t/=item.second.p.size();gs.push_back(std::move(item.second));}std::sort(gs.begin(),gs.end(),[](const G&a,const G&b){return std::tie(a.t,a.id)<std::tie(b.t,b.id);});result.stats.source_groups+=gs.size();std::vector<H> active,finished;
  for(std::size_t gi=0;gi<gs.size();++gi){++result.stats.groups_processed;const G&g=gs[gi];std::vector<H> next;std::set<std::size_t> established_used;for(const H&h:active){if(g.t-h.fit.t>c.maximum_gap_s){finished.push_back(h);continue;}struct A{std::size_t pi;double f,e,merit;};std::vector<A>a;for(auto pi:g.p){++result.stats.associations_tested;double pred=h.fit.f+h.fit.r*(p[pi].t-h.fit.t);double f=p[pi].raw+std::nearbyint((pred-p[pi].raw)/spacing)*spacing,e=f-pred,gate=c.residual_gate_hz+h.fit.u;if(std::abs(e)<=gate)a.push_back({pi,f,e,p[pi].w-e*e/(gate*gate)});}std::sort(a.begin(),a.end(),[](const A&x,const A&y){return std::tie(x.merit,x.pi)>std::tie(y.merit,y.pi);});bool advanced=false;for(std::size_t z=0;z<std::min(c.alternatives_per_hypothesis,a.size());++z){H q=h;q.p.push_back(a[z].pi);q.f.push_back(a[z].f);q.score+=a[z].merit;try{q.fit=fit(q,p,c,result.stats);}catch(...){continue;}if(q.fit.r>=c.minimum_rate_hz_per_s&&q.fit.r<=c.maximum_rate_hz_per_s&&q.fit.rms<=c.residual_gate_hz){next.push_back(std::move(q));advanced=true;if(h.p.size()>=3)established_used.insert(a[z].pi);}}if(!advanced)next.push_back(h);}
   for(auto now:g.p)if(!established_used.count(now)){for(std::size_t back=gi;back-->0;){double dt=p[now].t-gs[back].t;if(dt>c.maximum_gap_s)break;for(auto old:gs[back].p){double odt=p[now].t-p[old].t;if(odt<=0)continue;double rawrate=wrap(p[now].raw-p[old].raw,spacing)/odt;for(int shift=-1;shift<=1;++shift){double rate=rawrate+shift*spacing/odt;if(rate<c.minimum_rate_hz_per_s||rate>c.maximum_rate_hz_per_s)continue;H h;h.p={old,now};h.f={p[old].raw,p[old].raw+rate*odt};h.score=p[old].w+p[now].w;try{h.fit=fit(h,p,c,result.stats);}catch(...){continue;}next.push_back(std::move(h));++result.stats.births;}}break;}}
   std::sort(next.begin(),next.end(),[&](const H&a,const H&b){return better(a,b,p);});std::vector<H> unique;const std::size_t birth_reserve=std::min<std::size_t>(8,c.maximum_active_per_lane/3);for(auto&h:next){if(h.p.size()<=2)continue;bool duplicate=false;for(const auto&q:unique)if(h.p.back()==q.p.back()&&std::abs(h.fit.r-q.fit.r)<2&&std::abs(h.fit.f-q.fit.f)<50){duplicate=true;break;}if(!duplicate)unique.push_back(std::move(h));if(unique.size()==c.maximum_active_per_lane-birth_reserve)break;}for(auto&h:next){if(h.p.size()!=2)continue;bool duplicate=false;for(const auto&q:unique)if(h.p.back()==q.p.back()&&std::abs(h.fit.r-q.fit.r)<2&&std::abs(h.fit.f-q.fit.f)<50){duplicate=true;break;}if(!duplicate)unique.push_back(std::move(h));if(unique.size()==c.maximum_active_per_lane)break;}active=std::move(unique);result.stats.peak_active=std::max(result.stats.peak_active,active.size());}
  finished.insert(finished.end(),active.begin(),active.end());std::sort(finished.begin(),finished.end(),[&](const H&a,const H&b){return better(a,b,p);});std::set<std::string> signatures;for(const H&h:finished){double span=p[h.p.back()].t-p[h.p.front()].t;if(h.p.size()<c.minimum_support||span<c.minimum_span_s)continue;std::string sig;for(auto i:h.p)sig+=p[i].c->candidate_id;if(!signatures.insert(sig).second)continue;result.tracks.push_back(output(h,p,key,result.tracks.size(),spacing));}}
 std::set<std::string> used;for(const auto&t:result.tracks)for(const auto&p:t.points)used.insert(p.candidate_id);result.used_candidate_count=used.size();return result;}
} // namespace leo::adaptive::tracking::research::streaming_rolling
