[Service]
Environment=PYTHONPATH=/opt/leo-hard60/967566245590-r1/api/src:/opt/leo-v060-adaptive/a491b1ca7ee021e3e0e19a8c98becd2c9b1dae8b/src
ExecStart=
ExecStart=/usr/bin/env PYTHONDONTWRITEBYTECODE=1 LEO_WEB_DIST=/opt/leo-hard60/967566245590-r1/web/dist /opt/leo-tracker/current-api/.venv/bin/leo-api
