"""Figures and portable report for the recovered cyclic-phase representation."""

import base64
import csv
import html
import json
from collections import Counter

import matplotlib
import numpy as np
from phase_model import OUT

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402


def main():
    model = json.loads((OUT / "phase_model.json").read_text())
    with (OUT / "phase_indices.csv").open() as stream:
        observations = list(csv.DictReader(stream))
    seed = np.array(list(map(int, model["seed"])))
    words = np.array([list(map(int, w)) for w in model["generated_words"]])
    unmasked = (1 - words) ^ seed
    fig, axes = plt.subplots(1, 2, figsize=(13, 10), layout="constrained")
    for ax, matrix, title in zip(
        axes,
        [words, unmasked],
        ["Recovered 60-bit word", "After removing one fixed pattern"],
        strict=True,
    ):
        ax.imshow(matrix, aspect="auto", cmap="binary", vmin=0, vmax=1)
        ax.set_xlabel("Bit position (0–59)")
        ax.set_ylabel("Decoded phase index k (0–59)")
        ax.set_title(title)
    fig.suptitle(
        "Every recovered word is generated by a cyclic shift of one 60-bit pattern\n"
        "Left: Bₖ = 1 XOR S XOR rotate(S, k) · Right: rotate(S, k)"
    )
    fig.savefig(OUT / "phase_generator.png", dpi=160)
    plt.close(fig)
    names = ["S01", "S02", "S06", "S07", "S13", "S18", "S19", "S22", "S23"]
    matrix = np.full((len(names), 89), np.nan)
    for r in observations:
        if r["signal"] in names:
            matrix[names.index(r["signal"]), int(r["frame"])] = int(r["phase_index"])
    fig, ax = plt.subplots(figsize=(15, 5), layout="constrained")
    cmap = plt.get_cmap("twilight").copy()
    cmap.set_bad("#eeeeee")
    im = ax.imshow(matrix, aspect="auto", cmap=cmap, vmin=0, vmax=60, interpolation="nearest")
    ax.set_yticks(range(len(names)), names)
    ax.set_xlabel("Relative RF frame within each excerpt; rows have independent time origins")
    ax.set_title(
        "Recovered cyclic-phase states, retaining missing frames\n"
        "Grey = calibration frame or no qualified word; no gap interpolation"
    )
    fig.colorbar(im, ax=ax, label="Phase index k")
    fig.savefig(OUT / "phase_sequences.png", dpi=160)
    plt.close(fig)
    ds = Counter(int(r["phase_index"]) for r in observations if r["signal"] != "UT-ref")
    ut = Counter(int(r["phase_index"]) for r in observations if r["signal"] == "UT-ref")
    dictionary = [
        dict(
            phase_index=k,
            word=w,
            folded_family_index=min(k, 60 - k),
            ds_observations=ds[k],
            ut_observations=ut[k],
        )
        for k, w in enumerate(model["generated_words"])
    ]
    with (OUT / "phase_dictionary.csv").open("w") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(dictionary[0]))
        writer.writeheader()
        writer.writerows(dictionary)
    document = """<!doctype html><meta charset="utf-8"><title>Starlink phase-state finding</title>
<style>body{font:16px system-ui;margin:30px;max-width:1600px}img{max-width:100%}
table{border-collapse:collapse;font-size:13px}td,th{padding:8px;border:1px solid #ccc}
pre{white-space:pre-wrap}.scroll{overflow:auto;max-height:700px}</style>
<h1>The 60-bit words admit a 60-state cyclic-phase representation</h1>
<p>All 907 previously qualified observations (560 DS7/DS8 and 347 UT) match one generator exactly.
Two UT words fix the 60-bit seed after exploratory catalogue inspection; the formula predicts the
remaining word types, including state 17 absent from the accepted UT pool. This is an algebraic
representation of received patterns, not a decoded satellite ID, UTC or literal six-bit field.</p>
<p>Across fixed windows, 2,779 of 2,780 accepted window observations match the same model;
one shorter DS window differs by one bit and is retained as a discrepancy. These windows overlap
earlier evidence and are not independent trials. Multiple accepted UT windows in each of 338
frames agree exactly on the same word. Window position is not causing those word changes.</p>
<p>Chronological tests do not establish a counter or simple state recurrence. Applying the
post-header phase correction to the early header does not reveal stable fields in this assay.
The function of phase selection remains unknown; no user payload is decoded.</p>
<p><a href="phase_dictionary.csv">Complete state/word dictionary</a> ·
<a href="phase_indices.csv">Frame-by-frame decoded states</a> ·
<a href="phase_model.json">Model and provenance</a> ·
<a href="state_and_header.json">Temporal/header tests</a> ·
<a href="sequence_comparisons.json">Repeated-visit controls</a></p>"""
    document += "<pre>B_k[i] = 1 XOR S[i] XOR S[(i+k) mod 60]\nS = " + model["seed"] + "</pre>"
    for name in ["phase_generator", "phase_sequences"]:
        encoded = base64.b64encode((OUT / f"{name}.png").read_bytes()).decode()
        document += f'<img src="data:image/png;base64,{encoded}">'
    document += "<h2>State dictionary</h2><div class='scroll'><table>"
    document += "<tr>" + "".join(f"<th>{k}</th>" for k in dictionary[0]) + "</tr>"
    for row in dictionary:
        document += (
            "<tr>" + "".join(f"<td>{html.escape(str(v))}</td>" for v in row.values()) + "</tr>"
        )
    (OUT / "phase_report.html").write_text(document + "</table></div>")


if __name__ == "__main__":
    main()
