"""add durable single-owner acquisition operation queue

Revision ID: 63f8b6c1a902
Revises: 9b7e31a4c2d8
Create Date: 2026-08-21 08:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "63f8b6c1a902"
down_revision: str | Sequence[str] | None = "9b7e31a4c2d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "CREATE TABLE acquisition_operation ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
        "operation_key VARCHAR(160) NOT NULL, kind VARCHAR(32) NOT NULL, "
        "state VARCHAR(16) NOT NULL DEFAULT 'pending', payload JSONB NOT NULL, "
        "scheduled_for TIMESTAMPTZ NOT NULL, available_at TIMESTAMPTZ NOT NULL, "
        "priority INTEGER NOT NULL DEFAULT 0, attempt_count INTEGER NOT NULL DEFAULT 0, "
        "max_attempts INTEGER NOT NULL DEFAULT 3, lease_owner VARCHAR(128), "
        "lease_expires_at TIMESTAMPTZ, heartbeat_at TIMESTAMPTZ, "
        "started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, outcome TEXT, error TEXT, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), "
        "CONSTRAINT pk_acquisition_operation PRIMARY KEY (id), "
        "CONSTRAINT uq_acquisition_operation_operation_key UNIQUE (operation_key), "
        "CONSTRAINT ck_acquisition_operation_kind_values CHECK (kind IN "
        "('scheduled_recording','scanner_sweep','operator_once','qualification','soak','radio_probe')), "
        "CONSTRAINT ck_acquisition_operation_state_values CHECK (state IN "
        "('pending','leased','succeeded','failed','cancelled')), "
        "CONSTRAINT ck_acquisition_operation_attempt_bounds CHECK "
        "(attempt_count >= 0 AND max_attempts > 0), "
        "CONSTRAINT ck_acquisition_operation_lease_coherence CHECK "
        "((state='leased' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL) OR "
        "(state<>'leased' AND lease_owner IS NULL AND lease_expires_at IS NULL)))"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_acquisition_operation_single_lease "
        "ON acquisition_operation ((1)) WHERE state='leased'"
    )
    op.execute(
        "CREATE INDEX ix_acquisition_operation_claim ON acquisition_operation "
        "(state, available_at, priority, id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE acquisition_operation")
