"""initial catalog schema

Revision ID: f47b536afe98
Revises:
Create Date: 2026-08-19 02:00:14.236479
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f47b536afe98"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capture_profile",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_profile")),
        sa.UniqueConstraint("name", name=op.f("uq_capture_profile_name")),
    )
    op.create_table(
        "pipeline_release",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("code_revision", sa.String(length=128), nullable=False),
        sa.Column("environment_digest", sa.String(length=71), nullable=False),
        sa.Column("graph_digest", sa.String(length=71), nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_release")),
    )
    op.create_table(
        "radio",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("serial", sa.String(length=128), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radio")),
        sa.UniqueConstraint("serial", name=op.f("uq_radio_serial")),
    )
    op.create_table(
        "tag",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_tag")),
    )
    op.create_table(
        "capture_profile_revision",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=71), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["capture_profile.id"],
            name=op.f("fk_capture_profile_revision_profile_id_capture_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_profile_revision")),
        sa.UniqueConstraint(
            "profile_id", "digest", name=op.f("uq_capture_profile_revision_profile_id_digest")
        ),
        sa.UniqueConstraint(
            "profile_id",
            "revision_number",
            name=op.f("uq_capture_profile_revision_profile_id_revision_number"),
        ),
    )
    op.create_index(
        op.f("ix_capture_profile_revision_profile_id"),
        "capture_profile_revision",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "hardware_epoch",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("radio_id", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["radio_id"],
            ["radio.id"],
            name=op.f("fk_hardware_epoch_radio_id_radio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hardware_epoch")),
    )
    op.create_index(
        op.f("ix_hardware_epoch_radio_id"), "hardware_epoch", ["radio_id"], unique=False
    )
    op.create_table(
        "receiver_path",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("radio_id", sa.String(length=128), nullable=False),
        sa.Column("receiver_id", sa.SmallInteger(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["radio_id"],
            ["radio.id"],
            name=op.f("fk_receiver_path_radio_id_radio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receiver_path")),
        sa.UniqueConstraint(
            "radio_id", "receiver_id", name=op.f("uq_receiver_path_radio_id_receiver_id")
        ),
    )
    op.create_index(op.f("ix_receiver_path_radio_id"), "receiver_path", ["radio_id"], unique=False)
    op.create_table(
        "capture_session",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("profile_revision_id", sa.BigInteger(), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("requested_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bundle_uri", sa.Text(), nullable=True),
        sa.Column("manifest_digest", sa.String(length=71), nullable=True),
        sa.Column("allocated_bytes", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("raw_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("purge_claim_token", sa.String(length=128), nullable=True),
        sa.Column("purge_claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_previous_state", sa.String(length=16), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('live', 'test', 'import')",
            name=op.f("ck_capture_session_source_type_values"),
        ),
        sa.CheckConstraint(
            "state IN ('committed', 'degraded', 'failed', 'purging', 'purged')",
            name=op.f("ck_capture_session_state_values"),
        ),
        sa.CheckConstraint(
            "allocated_bytes >= 0",
            name=op.f("ck_capture_session_nonnegative_allocated_bytes"),
        ),
        sa.CheckConstraint(
            "(state = 'purging' AND purge_claim_token IS NOT NULL "
            "AND purge_claim_expires_at IS NOT NULL AND purge_previous_state IS NOT NULL) "
            "OR (state <> 'purging' AND purge_claim_token IS NULL "
            "AND purge_claim_expires_at IS NULL AND purge_previous_state IS NULL)",
            name=op.f("ck_capture_session_purge_claim_coherent"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_revision_id"],
            ["capture_profile_revision.id"],
            name=op.f("fk_capture_session_profile_revision_id_capture_profile_revision"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_session")),
    )
    op.create_index(
        op.f("ix_capture_session_created_at"), "capture_session", ["created_at"], unique=False
    )
    op.create_index(
        "ix_capture_session_created_source_state",
        "capture_session",
        ["created_at", "source_type", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capture_session_profile_revision_id"),
        "capture_session",
        ["profile_revision_id"],
        unique=False,
    )
    op.create_table(
        "frequency_calibration",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("receiver_path_id", sa.BigInteger(), nullable=False),
        sa.Column("hardware_epoch_id", sa.BigInteger(), nullable=True),
        sa.Column("center_offset_hz", sa.Float(), nullable=False),
        sa.Column("uncertainty_hz", sa.Float(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_uri", sa.Text(), nullable=True),
        sa.Column("evidence_digest", sa.String(length=71), nullable=True),
        sa.ForeignKeyConstraint(
            ["hardware_epoch_id"],
            ["hardware_epoch.id"],
            name=op.f("fk_frequency_calibration_hardware_epoch_id_hardware_epoch"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["receiver_path_id"],
            ["receiver_path.id"],
            name=op.f("fk_frequency_calibration_receiver_path_id_receiver_path"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_frequency_calibration")),
    )
    op.create_index(
        op.f("ix_frequency_calibration_hardware_epoch_id"),
        "frequency_calibration",
        ["hardware_epoch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_frequency_calibration_receiver_path_id"),
        "frequency_calibration",
        ["receiver_path_id"],
        unique=False,
    )
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("pipeline_release_id", sa.String(length=128), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("input_manifest_digest", sa.String(length=71), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manifest_uri", sa.Text(), nullable=True),
        sa.Column("manifest_digest", sa.String(length=71), nullable=True),
        sa.Column("failure", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_analysis_run_state_values"),
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_release_id"],
            ["pipeline_release.id"],
            name=op.f("fk_analysis_run_pipeline_release_id_pipeline_release"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_analysis_run_session_id_capture_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run")),
    )
    op.create_index(
        op.f("ix_analysis_run_pipeline_release_id"),
        "analysis_run",
        ["pipeline_release_id"],
        unique=False,
    )
    op.create_index(
        "ix_analysis_run_session_created",
        "analysis_run",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_analysis_run_active_session",
        "analysis_run",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('pending', 'running')"),
    )
    op.create_table(
        "radio_stream",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("radio_id", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("receiver_ids", sa.ARRAY(sa.SmallInteger()), nullable=False),
        sa.Column("sample_rate_hz", sa.Integer(), nullable=False),
        sa.Column("captured_sample_count", sa.BigInteger(), nullable=False),
        sa.Column("observed_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["radio_id"],
            ["radio.id"],
            name=op.f("fk_radio_stream_radio_id_radio"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_radio_stream_session_id_capture_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radio_stream")),
        sa.UniqueConstraint(
            "session_id", "radio_id", name=op.f("uq_radio_stream_session_id_radio_id")
        ),
    )
    op.create_index(op.f("ix_radio_stream_radio_id"), "radio_stream", ["radio_id"], unique=False)
    op.create_index(
        op.f("ix_radio_stream_session_id"), "radio_stream", ["session_id"], unique=False
    )
    op.create_table(
        "retention_event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("bytes_reclaimed", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_retention_event_session_id_capture_session"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_event")),
    )
    op.create_index(
        op.f("ix_retention_event_created_at"), "retention_event", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_retention_event_session_id"), "retention_event", ["session_id"], unique=False
    )
    op.create_table(
        "retention_hold",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_retention_hold_session_id_capture_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_hold")),
    )
    op.create_index(
        op.f("ix_retention_hold_session_id"), "retention_hold", ["session_id"], unique=False
    )
    op.create_index(
        "uq_retention_hold_active_session",
        "retention_hold",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "session_tag",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("tag_name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_session_tag_session_id_capture_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_name"], ["tag.name"], name=op.f("fk_session_tag_tag_name_tag"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id", "tag_name", name=op.f("pk_session_tag")),
    )
    op.create_table(
        "analysis_product",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("stage_key", sa.String(length=128), nullable=False),
        sa.Column("scope_key", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("logical_uri", sa.Text(), nullable=False),
        sa.Column("digest", sa.String(length=71), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("purge_claim_token", sa.String(length=128), nullable=True),
        sa.Column("purge_claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "byte_size >= 0", name=op.f("ck_analysis_product_nonnegative_byte_size")
        ),
        sa.CheckConstraint(
            "schema_version > 0", name=op.f("ck_analysis_product_positive_schema_version")
        ),
        sa.CheckConstraint(
            "(purge_claim_token IS NULL AND purge_claim_expires_at IS NULL) OR "
            "(purge_claim_token IS NOT NULL AND purge_claim_expires_at IS NOT NULL)",
            name=op.f("ck_analysis_product_purge_claim_coherent"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_analysis_product_run_id_analysis_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_product")),
        sa.UniqueConstraint(
            "run_id",
            "stage_key",
            "scope_key",
            "kind",
            "schema_version",
            name=op.f("uq_analysis_product_run_id_stage_key_scope_key_kind_schema_version"),
        ),
    )
    op.create_index(
        op.f("ix_analysis_product_run_id"), "analysis_product", ["run_id"], unique=False
    )
    op.create_table(
        "analysis_summary",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("mean_power_dbfs", sa.Float(), nullable=True),
        sa.Column("best_qam_accuracy", sa.Float(), nullable=True),
        sa.Column("best_cfo_hz", sa.Float(), nullable=True),
        sa.Column("doppler_slope_hz_s", sa.Float(), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=True),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_analysis_summary_run_id_analysis_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_analysis_summary_session_id_capture_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_analysis_summary")),
        sa.UniqueConstraint("run_id", name=op.f("uq_analysis_summary_run_id")),
    )
    op.create_index(
        op.f("ix_analysis_summary_best_cfo_hz"), "analysis_summary", ["best_cfo_hz"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_summary_best_qam_accuracy"),
        "analysis_summary",
        ["best_qam_accuracy"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_summary_candidate_count"),
        "analysis_summary",
        ["candidate_count"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_summary_coverage"), "analysis_summary", ["coverage"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_summary_doppler_slope_hz_s"),
        "analysis_summary",
        ["doppler_slope_hz_s"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_summary_mean_power_dbfs"),
        "analysis_summary",
        ["mean_power_dbfs"],
        unique=False,
    )
    op.create_table(
        "current_analysis",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_current_analysis_run_id_analysis_run"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["capture_session.id"],
            name=op.f("fk_current_analysis_session_id_capture_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_current_analysis")),
        sa.UniqueConstraint("run_id", name=op.f("uq_current_analysis_run_id")),
    )
    op.create_table(
        "processing_job",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("stage_key", sa.String(length=128), nullable=False),
        sa.Column("scope_key", sa.String(length=256), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'leased' AND lease_owner IS NOT NULL "
            "AND lease_expires_at IS NOT NULL) OR "
            "(state <> 'leased' AND lease_owner IS NULL "
            "AND lease_expires_at IS NULL)",
            name=op.f("ck_processing_job_lease_state_coherence"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'leased', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_processing_job_state_values"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_processing_job_nonnegative_attempt_count")
        ),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_processing_job_positive_max_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_processing_job_run_id_analysis_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_job")),
        sa.UniqueConstraint(
            "run_id",
            "stage_key",
            "scope_key",
            name=op.f("uq_processing_job_run_id_stage_key_scope_key"),
        ),
    )
    op.create_index(
        "ix_processing_job_claim",
        "processing_job",
        ["state", "available_at", "priority", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_processing_job_run_id"), "processing_job", ["run_id"], unique=False)
    op.create_table(
        "recording_chunk",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("stream_id", sa.String(length=128), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("sample_start", sa.BigInteger(), nullable=False),
        sa.Column("sample_count", sa.BigInteger(), nullable=False),
        sa.Column("logical_uri", sa.Text(), nullable=False),
        sa.Column("compressed_digest", sa.String(length=71), nullable=False),
        sa.Column("uncompressed_digest", sa.String(length=71), nullable=False),
        sa.Column("compressed_bytes", sa.BigInteger(), nullable=False),
        sa.Column("uncompressed_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["radio_stream.id"],
            name=op.f("fk_recording_chunk_stream_id_radio_stream"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recording_chunk")),
        sa.UniqueConstraint(
            "stream_id", "chunk_index", name=op.f("uq_recording_chunk_stream_id_chunk_index")
        ),
    )
    op.create_index(
        op.f("ix_recording_chunk_stream_id"), "recording_chunk", ["stream_id"], unique=False
    )
    op.create_table(
        "processing_job_attempt",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["processing_job.id"],
            name=op.f("fk_processing_job_attempt_job_id_processing_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_job_attempt")),
        sa.UniqueConstraint(
            "job_id", "attempt_number", name=op.f("uq_processing_job_attempt_job_id_attempt_number")
        ),
    )
    op.create_index(
        op.f("ix_processing_job_attempt_job_id"), "processing_job_attempt", ["job_id"], unique=False
    )
    op.create_table(
        "processing_job_dependency",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("depends_on_job_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "job_id <> depends_on_job_id", name=op.f("ck_processing_job_dependency_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_job_id"],
            ["processing_job.id"],
            name=op.f("fk_processing_job_dependency_depends_on_job_id_processing_job"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["processing_job.id"],
            name=op.f("fk_processing_job_dependency_job_id_processing_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "job_id", "depends_on_job_id", name=op.f("pk_processing_job_dependency")
        ),
    )
    op.create_table(
        "product_dependency",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("input_product_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "product_id <> input_product_id", name=op.f("ck_product_dependency_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["input_product_id"],
            ["analysis_product.id"],
            name=op.f("fk_product_dependency_input_product_id_analysis_product"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["analysis_product.id"],
            name=op.f("fk_product_dependency_product_id_analysis_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "input_product_id", name=op.f("pk_product_dependency")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_dependency")
    op.drop_table("processing_job_dependency")
    op.drop_index(op.f("ix_processing_job_attempt_job_id"), table_name="processing_job_attempt")
    op.drop_table("processing_job_attempt")
    op.drop_index(op.f("ix_recording_chunk_stream_id"), table_name="recording_chunk")
    op.drop_table("recording_chunk")
    op.drop_index(op.f("ix_processing_job_run_id"), table_name="processing_job")
    op.drop_index("ix_processing_job_claim", table_name="processing_job")
    op.drop_table("processing_job")
    op.drop_table("current_analysis")
    op.drop_index(op.f("ix_analysis_summary_mean_power_dbfs"), table_name="analysis_summary")
    op.drop_index(op.f("ix_analysis_summary_doppler_slope_hz_s"), table_name="analysis_summary")
    op.drop_index(op.f("ix_analysis_summary_coverage"), table_name="analysis_summary")
    op.drop_index(op.f("ix_analysis_summary_candidate_count"), table_name="analysis_summary")
    op.drop_index(op.f("ix_analysis_summary_best_qam_accuracy"), table_name="analysis_summary")
    op.drop_index(op.f("ix_analysis_summary_best_cfo_hz"), table_name="analysis_summary")
    op.drop_table("analysis_summary")
    op.drop_index(op.f("ix_analysis_product_run_id"), table_name="analysis_product")
    op.drop_table("analysis_product")
    op.drop_table("session_tag")
    op.drop_index(
        "uq_retention_hold_active_session",
        table_name="retention_hold",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_index(op.f("ix_retention_hold_session_id"), table_name="retention_hold")
    op.drop_table("retention_hold")
    op.drop_index(op.f("ix_retention_event_session_id"), table_name="retention_event")
    op.drop_index(op.f("ix_retention_event_created_at"), table_name="retention_event")
    op.drop_table("retention_event")
    op.drop_index(op.f("ix_radio_stream_session_id"), table_name="radio_stream")
    op.drop_index(op.f("ix_radio_stream_radio_id"), table_name="radio_stream")
    op.drop_table("radio_stream")
    op.drop_index(
        "uq_analysis_run_active_session",
        table_name="analysis_run",
        postgresql_where=sa.text("state IN ('pending', 'running')"),
    )
    op.drop_index("ix_analysis_run_session_created", table_name="analysis_run")
    op.drop_index(op.f("ix_analysis_run_pipeline_release_id"), table_name="analysis_run")
    op.drop_table("analysis_run")
    op.drop_index(
        op.f("ix_frequency_calibration_receiver_path_id"), table_name="frequency_calibration"
    )
    op.drop_index(
        op.f("ix_frequency_calibration_hardware_epoch_id"), table_name="frequency_calibration"
    )
    op.drop_table("frequency_calibration")
    op.drop_index(op.f("ix_capture_session_profile_revision_id"), table_name="capture_session")
    op.drop_index("ix_capture_session_created_source_state", table_name="capture_session")
    op.drop_index(op.f("ix_capture_session_created_at"), table_name="capture_session")
    op.drop_table("capture_session")
    op.drop_index(op.f("ix_receiver_path_radio_id"), table_name="receiver_path")
    op.drop_table("receiver_path")
    op.drop_index(op.f("ix_hardware_epoch_radio_id"), table_name="hardware_epoch")
    op.drop_table("hardware_epoch")
    op.drop_index(
        op.f("ix_capture_profile_revision_profile_id"), table_name="capture_profile_revision"
    )
    op.drop_table("capture_profile_revision")
    op.drop_table("tag")
    op.drop_table("radio")
    op.drop_table("pipeline_release")
    op.drop_table("capture_profile")
    # ### end Alembic commands ###
