"""Pure Starlink known-pilot numerical primitives."""

from leo.analysis.starlink.acquisition import (
    AcquisitionCandidate,
    NumericalStatus,
    ReceiverFrequencyCalibration,
    SymbolwiseAcquisitionConfig,
    SymbolwiseAcquisitionResult,
    acquire_symbolwise,
    conditioned_frame_score,
    normalized_frame_score,
)
from leo.analysis.starlink.corpus import (
    CorpusPreflightReport,
    FixturePreflight,
    FixturePreflightStatus,
    RequiredFixtureError,
    inspect_corpus,
    preflight_corpus,
)
from leo.analysis.starlink.templates import (
    CONTROL_SYMBOL_ROLL,
    CYCLIC_PREFIX_DURATION_S,
    FRAME_RATE_HZ,
    OFDM_SYMBOL_DURATION_S,
    QIN_ARXIV_ID,
    SUBCARRIER_SPACING_HZ,
    StarlinkEdge,
    edge_frequencies_hz,
    qin_edge_pilot_frame,
    qin_edge_pilot_indices,
    qin_edge_pilot_states,
    qin_edge_pilot_symbols,
    template_sha256,
)

__all__ = [
    "CONTROL_SYMBOL_ROLL",
    "CYCLIC_PREFIX_DURATION_S",
    "FRAME_RATE_HZ",
    "OFDM_SYMBOL_DURATION_S",
    "QIN_ARXIV_ID",
    "SUBCARRIER_SPACING_HZ",
    "AcquisitionCandidate",
    "CorpusPreflightReport",
    "FixturePreflight",
    "FixturePreflightStatus",
    "NumericalStatus",
    "ReceiverFrequencyCalibration",
    "RequiredFixtureError",
    "StarlinkEdge",
    "SymbolwiseAcquisitionConfig",
    "SymbolwiseAcquisitionResult",
    "acquire_symbolwise",
    "conditioned_frame_score",
    "edge_frequencies_hz",
    "inspect_corpus",
    "normalized_frame_score",
    "preflight_corpus",
    "qin_edge_pilot_frame",
    "qin_edge_pilot_indices",
    "qin_edge_pilot_states",
    "qin_edge_pilot_symbols",
    "template_sha256",
]
