#ifndef LEO_NATIVE_GLRT_PRIVATE_NAMESPACE_H
#define LEO_NATIVE_GLRT_PRIVATE_NAMESPACE_H

/* The frozen detector was originally an executable and used externally linked
 * helper names. Prefix every such name when it is embedded in the production
 * archive so it can coexist with the legacy native-presence library. */
#define leo_conditioned_czt_magnitudes leo_native_glrt_private_conditioned_czt_magnitudes
#define leo_fft_backend_identity leo_native_glrt_private_fft_backend_identity
#define leo_fft_forward leo_native_glrt_private_fft_forward
#define leo_fft_forward_range leo_native_glrt_private_fft_forward_range
#define leo_fft_free leo_native_glrt_private_fft_free
#define leo_fft_init leo_native_glrt_private_fft_init
#define leo_full_search_retain_peaks leo_native_glrt_private_full_search_retain_peaks
#define leo_full_search_run leo_native_glrt_private_full_search_run
#define leo_full_search_run_ci16 leo_native_glrt_private_full_search_run_ci16
#define leo_full_search_run_prepared leo_native_glrt_private_full_search_run_prepared
#define leo_presence_coarse leo_native_glrt_private_presence_coarse
#define leo_presence_coarse_ci16 leo_native_glrt_private_presence_coarse_ci16
#define leo_presence_confirm_ci16 leo_native_glrt_private_presence_confirm_ci16
#define leo_presence_create leo_native_glrt_private_presence_create
#define leo_presence_destroy leo_native_glrt_private_presence_destroy
#define leo_presence_get_nuisance leo_native_glrt_private_presence_get_nuisance
#define leo_presence_get_profile leo_native_glrt_private_presence_get_profile
#define leo_presence_glrt leo_native_glrt_private_presence_glrt
#define leo_presence_run leo_native_glrt_private_presence_run
#define leo_presence_run_ci16 leo_native_glrt_private_presence_run_ci16
#define leo_proposal_create leo_native_glrt_private_proposal_create
#define leo_proposal_destroy leo_native_glrt_private_proposal_destroy
#define leo_proposal_top4 leo_native_glrt_private_proposal_top4
#define leo_tracked_centers leo_native_glrt_private_tracked_centers
#define leo_translate_center leo_native_glrt_private_translate_center

#endif
