"""Describe the score-selected wider-region rescue without changing cohort metrics."""

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent


def main():
    result = json.loads((HERE / "result.json").read_text())
    regional = json.loads((HERE / "regions.json").read_text())
    baseline = json.loads(
        (HERE.parent / "2026_10_08_position_error_iter45/baselines/DS16-046.json").read_text()
    )
    stages = {"Previous final": result["previous_operational"]}
    stages["New regional"] = {
        a["name"]: dict(
            error_km=a["selected"]["horizontal_error_m"] / 1000,
            posterior_rms_hz=a["selected"]["posterior_rms_hz"],
        )
        for a in regional["methods"][0]["arms"]
    }
    stages.update(result["upstream"]["stages"])
    stages.update(result["extension"]["stages"])
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.5), layout="constrained")
    for arm in ("fitted-c", "zero-c"):
        for ax, field in zip(axes, ("error_km", "posterior_rms_hz"), strict=True):
            ax.plot(
                range(len(stages)), [r[arm][field] for r in stages.values()], marker="o", label=arm
            )
    for ax in axes:
        ax.set_xticks(range(len(stages)), stages, rotation=40, ha="right", fontsize=8)
        ax.grid(alpha=0.2)
        ax.legend()
    axes[0].set(yscale="log", ylabel="Position error km")
    axes[1].set_ylabel("Posterior frequency RMS Hz")
    fig.savefig(HERE / "rescue.png", dpi=160)
    text = """# Iteration 48: preserving a wider region rescues DS16-046

**Adding 50 km-separated regions reduces fitted-c error from 265.789 km to
0.798 km, and zero-c from 261.743 km to 2.128 km.** The new region wins by the
unchanged model score; reference position is used only to report error afterward.
This is a consumed-case diagnostic, not yet a dataset-wide qualified replacement.

![Position and frequency fit through the unchanged downstream stages](rescue.png)

## What changed

Commit `105203307` froze this test before fitting. The 400-point 40/20/10/5 km grid,
observations, priors, clock model, hard60 bounds and per-fit budgets stay unchanged.
A replay retains three regions at minimum separation 50 km instead of 25 km.
It includes the distant (30,170) km region, the correct neighborhood at (−90,−90)
km and another region at (110,90) km. The old baseline beats the old sep25 replay
in both arms, verified before fitting. Comparing it with the new sep50 replay
therefore preserves all previously winning regional choices on this case.

This adds regional fitting work; it is not an equal-total-compute comparison.
The spatial grid budget remains exactly 400 ordered points. The extra candidate
bank is generated by the existing procedure, not chosen using reference position.
The added arms have matched observations, banks, priors, starts and budgets;
zero-c also locks RF-time terms in downstream stages.

Both arms select `point:-90:-90` in the added region set. The regional solution
already reduces errors to 1.807 km fitted-c and 3.445 km zero-c. The unchanged
joint-clock/pruning/RF-time/satellite-slope pipeline then reaches 0.798/2.128 km.
Every one of its 12 paired stage fits is independently converged; no fallback is
needed. Production and frozen full-dataset benchmark results remain unchanged.

| Arm | Old regional score | New regional score | Prior final error km | New final error km |
|---|---:|---:|---:|---:|
"""
    for arm in ("fitted-c", "zero-c"):
        old = next(a["selected"] for a in baseline["methods"][0]["arms"] if a["name"] == arm)
        new = next(a["selected"] for a in regional["methods"][0]["arms"] if a["name"] == arm)
        text += (
            f"| {arm} | {old['selection_score']:.3f} | {new['selection_score']:.3f} | "
            f"{result['previous_operational'][arm]['error_km']:.6f} | "
            f"{result['extension']['operational'][arm]['error_km']:.6f} |\n"
        )
    text += """
## Interpretation and remaining work

This verifies the retention diagnosis from iteration47: the useful region was
already sampled and refined, but never received final fitting. Once retained,
the same score selects it without a reference-location initializer. It does not
show that 50 km separation alone is globally best: broader separation can lose
nearby alternatives, so a general policy must preserve the existing region sets
and add wider ones, then select eligible finalists by score.

Frequency RMS also improves, but it is reported separately: the final fitted-c
RMS falls from 158.248 to 99.322 Hz; zero-c from 174.035 to 144.944 Hz. Model-stage
objectives are not compared across different candidate banks or priors as an
accuracy proxy. The regional selection above follows the existing scoring policy.

Next, evaluate the additive wider-region policy on the full DS16/DS17/DS18 corpus,
preserving all membership and exposure labels, c ablations, failures and paired
regressions. The independent DS18 likelihood-ranking failure remains unresolved;
this single rescue is not substituted into its benchmark or the pooled mean.

[result.json](result.json) records every downstream fit and the exact-grid check;
[regions.json](regions.json) contains regional starts and calibration receipts.
All frozen hashes and zero-c locks pass. The plot was inspected and Ruff passes.
No public contract, production setting, golden fixture, QNAP data or RF collection
changed. The deployed fitted-c default and longest-16-track PNG limit remain intact.
"""
    (HERE / "README.md").write_text(text)


if __name__ == "__main__":
    main()
