"""Verify archive bytes and generate a navigable inventory without executing payloads."""
import hashlib
import json
import re
import zipfile
from collections import Counter
from datetime import UTC, datetime
from urllib.parse import urlsplit

from collect import BASE


def classify(url, raw):
    if not raw:
        return 'empty-response'
    if urlsplit(url).path.lower().endswith('.pdf') and not raw.startswith(b'%PDF-'):
        return 'invalid-pdf-response'
    if raw.startswith(b'\x7fELF'):
        return 'ELF'
    if raw.startswith(b'%PDF-'):
        return 'PDF'
    if raw.startswith(b'PK\x03\x04'):
        return 'ZIP'
    if raw.startswith(b'\x1f\x8b'):
        return 'gzip'
    if raw.startswith((b'\xff\xd8\xff', b'\x89PNG', b'GIF8')):
        return 'image'
    if url.startswith('https://x.com/search') and b'full_text:' not in raw:
        return 'X-search-without-posts'
    return 'other'


def main():
    resources = {}
    for name in ('manifest.json', 'additional-manifest.json', 'supplement-manifest.json',
                 'search-manifest.json', 'video-manifest.json'):
        path = BASE / name
        if path.exists():
            for row in json.loads(path.read_text())['resources']:
                resources[row['url']] = dict(row)
    counts, issues, archives = Counter(), [], []
    for url, row in resources.items():
        if row['status'] != 'downloaded':
            issues.append(dict(url=url, issue=row['error']))
            counts['failed'] += 1
            continue
        raw = (BASE / row['path']).read_bytes()
        assert len(raw) == row['bytes'], row['path']
        assert hashlib.sha256(raw).hexdigest() == row['sha256'], row['path']
        row['kind'] = classify(url, raw)
        counts[row['kind']] += 1
        if row['kind'] in ('invalid-pdf-response', 'X-search-without-posts', 'empty-response'):
            issues.append(dict(url=url, issue=row['kind']))
        if row['kind'] == 'ZIP':
            with zipfile.ZipFile(BASE / row['path']) as archive:
                archives.append(dict(url=url, path=row['path'], members=archive.namelist()))
    stats = dict(verified_utc=datetime.now(UTC).isoformat(), unique_urls=len(resources),
                 downloaded=sum(r['status'] == 'downloaded' for r in resources.values()),
                 bytes=sum(r.get('bytes', 0) for r in resources.values()),
                 classifications=dict(counts), issues=issues, zip_inventories=archives)
    (BASE / 'audit.json').write_text(json.dumps(stats, indent=2) + '\n')
    lines = ['# Download inventory', '',
             'Generated by `audit.py`. Raw objects are local and Git-ignored. '
             'HTTP success alone does not validate content; see `audit.json`.', '',
             '## Articles', '', '| Date | Article | Local text |', '|---|---|---|']
    for a in json.loads((BASE / 'articles.json').read_text()):
        lines.append(f'| {a["date"][:10]} | [{a["title"]}]({a["url"]}) | '
                     f'[text]({a["text"]}) |')
    lines += ['', '## Forum topics', '',
              'This is an acquisition inventory, not an endorsement. '
              'User replies and unrelated/spam threads are not Kutkov evidence.', '',
              '| Topic | Local text |', '|---|---|']
    for path in sorted((BASE / 'local').glob('topic-*.txt')):
        tid = path.stem.removeprefix('topic-')
        title = path.read_text().splitlines()[0].replace('|', '\\|')
        lines.append(f'| [{title}](https://olegkutkov.me/forum/index.php?topic={tid}) '
                     f'| [text](local/{path.name}) |')
    lines += ['', '## X posts', '',
              'Archived page responses may include other authors’ replies. '
              'Extracted text is in `local/x-posts.json`.', '']
    for row in resources.values():
        if re.match(r'https://(?:x|twitter)\.com/olegkutkov/status/\d+', row['url']):
            lines.append(f'- [Source]({row["url"]}) — [archived HTML]({row["path"]})')
    lines += ['', '## Resources', '', '| Kind/status | Source | Local object | Bytes |',
              '|---|---|---|---:|']
    for row in sorted(resources.values(), key=lambda r: r['url']):
        local = f'[file]({row["path"]})' if row['status'] == 'downloaded' else 'Unavailable'
        lines.append(f'| {row.get("kind", row["status"])} | '
                     f'[source]({row["url"]}) | {local} | {row.get("bytes", 0)} |')
    (BASE / 'INDEX.md').write_text('\n'.join(lines) + '\n')
    print(json.dumps({k: v for k, v in stats.items() if k not in ('issues', 'zip_inventories')}))


if __name__ == '__main__':
    main()
