"""Pure Standard GLRT64 receiver-path and aggregate computations."""

from leo.analysis.standard.analyzers import (
    STANDARD_V2_ANALYZERS,
    production_standard_v2_configuration,
    production_standard_v2_registry,
)
from leo.analysis.standard.codecs import decode_standard_product
from leo.analysis.standard.configuration import (
    RECEIVER_STANDARD_RATE_DERIVED_FIELDS,
    parse_receiver_standard_config,
    production_receiver_standard_config,
    production_receiver_standard_stage_configuration,
    production_receiver_standard_waterfall_config,
    require_receiver_standard_sample_rate,
    resolve_receiver_standard_sample_rate,
)
from leo.analysis.standard.probes import build_probe_schedule
from leo.analysis.standard.products import (
    GLRT64_TRAJECTORY_TABLE_PRODUCT,
    KALMAN_TRACKING_PRODUCT,
    NUMERICAL_WATERFALL_PRODUCT,
    PAIRED_REPORT_INPUT,
    PAIRED_REPORT_PRODUCT,
    PATH_INPUT_BIND_PRODUCT,
    PATH_PRESENTATION_INPUTS,
    PATH_PRESENTATION_PRODUCT,
    PATH_REPORT_INPUTS,
    PATH_REPORT_PRODUCT,
    PILOT_SCAN_INPUTS,
    PILOT_SCAN_PRODUCT,
    POWER_INPUTS,
    POWER_OUTPUTS,
    POWER_TIMELINE_PRODUCT,
    PROBE_SCHEDULE_INPUTS,
    PROBE_SCHEDULE_OUTPUTS,
    PROBE_SCHEDULE_PRODUCT,
    QUALITY_INPUTS,
    QUALITY_OUTPUTS,
    QUALITY_PRODUCT,
    RADIO_REPORT_INPUT,
    RADIO_REPORT_PRODUCT,
    STANDARD_SOURCE_BOUND_STAGE_OUTPUTS,
    TRAJECTORY_BANK_INPUTS,
    TRAJECTORY_BANK_PRODUCT,
    TRAJECTORY_FEEDBACK_INPUTS,
    TRAJECTORY_FEEDBACK_OUTPUTS,
    TRAJECTORY_FEEDBACK_PRODUCT,
    WATERFALL_INPUTS,
    WATERFALL_OUTPUTS,
)
from leo.analysis.standard.reducers import reduce_paired_radios, reduce_radio
from leo.analysis.standard.reports import (
    PathReportInputs,
    build_path_standard_report,
)
from leo.analysis.standard.runner import (
    ReceiverStandardConfig,
    ReceiverStandardResult,
    SingleReceiverIqReader,
    receiver_standard_configuration_digest,
    receiver_standard_implementation_digest,
    run_receiver_standard,
)
from leo.analysis.standard.source_bindings import (
    STANDARD_SOURCE_BINDING_SPECS,
    build_standard_source_binding,
    build_standard_source_bindings,
    verify_standard_source_bindings,
)

__all__ = [
    "PathReportInputs",
    "STANDARD_V2_ANALYZERS",
    "PATH_INPUT_BIND_PRODUCT",
    "PATH_PRESENTATION_INPUTS",
    "PATH_PRESENTATION_PRODUCT",
    "PATH_REPORT_INPUTS",
    "PATH_REPORT_PRODUCT",
    "PAIRED_REPORT_INPUT",
    "PAIRED_REPORT_PRODUCT",
    "PILOT_SCAN_INPUTS",
    "PILOT_SCAN_PRODUCT",
    "POWER_TIMELINE_PRODUCT",
    "POWER_INPUTS",
    "POWER_OUTPUTS",
    "PROBE_SCHEDULE_INPUTS",
    "PROBE_SCHEDULE_OUTPUTS",
    "PROBE_SCHEDULE_PRODUCT",
    "QUALITY_PRODUCT",
    "QUALITY_INPUTS",
    "QUALITY_OUTPUTS",
    "RADIO_REPORT_INPUT",
    "RADIO_REPORT_PRODUCT",
    "RECEIVER_STANDARD_RATE_DERIVED_FIELDS",
    "NUMERICAL_WATERFALL_PRODUCT",
    "GLRT64_TRAJECTORY_TABLE_PRODUCT",
    "KALMAN_TRACKING_PRODUCT",
    "ReceiverStandardConfig",
    "ReceiverStandardResult",
    "SingleReceiverIqReader",
    "STANDARD_SOURCE_BINDING_SPECS",
    "STANDARD_SOURCE_BOUND_STAGE_OUTPUTS",
    "TRAJECTORY_BANK_INPUTS",
    "TRAJECTORY_BANK_PRODUCT",
    "TRAJECTORY_FEEDBACK_INPUTS",
    "TRAJECTORY_FEEDBACK_OUTPUTS",
    "TRAJECTORY_FEEDBACK_PRODUCT",
    "WATERFALL_INPUTS",
    "WATERFALL_OUTPUTS",
    "build_standard_source_binding",
    "build_standard_source_bindings",
    "decode_standard_product",
    "build_path_standard_report",
    "build_probe_schedule",
    "reduce_paired_radios",
    "reduce_radio",
    "production_standard_v2_configuration",
    "production_standard_v2_registry",
    "parse_receiver_standard_config",
    "production_receiver_standard_config",
    "production_receiver_standard_stage_configuration",
    "production_receiver_standard_waterfall_config",
    "require_receiver_standard_sample_rate",
    "receiver_standard_configuration_digest",
    "receiver_standard_implementation_digest",
    "run_receiver_standard",
    "resolve_receiver_standard_sample_rate",
    "verify_standard_source_bindings",
]
